Alloy Transition
marlinprotocol/serverless-gateway pull request #12
Opened 2024-11-19 05:30 UTC by arnav-deep

Transition from Ethers to ALloy and use multi-txn-block lib for sending transactions in the same block and managing confirmations.

2024-12-05 15:44 UTC, vg-27 requested changes

2024-12-05 15:44 UTC, vg-27 commented on src/api_impl.rs
> +        let gateways_contract = Arc::new(GatewaysContract::new(
can't we create gateway contract object once and use it for all chains.

2024-12-05 15:44 UTC, vg-27 commented on src/api_impl.rs
> +        .unwrap();
error handling?

2024-12-05 15:44 UTC, vg-27 commented on src/api_impl.rs
> +        .unwrap();
error handling?

2024-12-05 15:44 UTC, vg-27 commented on src/common_chain_interaction.rs
> +        txn_data.extend(encoded_tokens[32..].to_vec());
isn't this auto generated using contract abi ? should avoid it doing ourself, given lib is there.

2024-12-10 16:15 UTC, arnav-deep commented on src/main.rs
> +use tokio::sync::RwLock as TokioRwLock;
Yeah, updated

2024-12-10 16:29 UTC, arnav-deep commented on src/api_impl.rs
> +        let gateways_contract = Arc::new(GatewaysContract::new(
The `gateways_contract` object gets moved in the `call()` method below and gives the `value moved` compile error. Tried cloning and it didn't work.

2024-12-10 16:31 UTC, arnav-deep commented on src/api_impl.rs
> +        .unwrap();
Added

2024-12-10 16:34 UTC, arnav-deep commented on src/api_impl.rs
> +        .unwrap();
Added

2024-12-13 05:23 UTC, vg-27 reviewed
suggested changes should solve the issue of GatewayContract object recreation. 

this [comment](https://github.com/marlinprotocol/serverless-gateway/pull/12/files/b3d7c68f9ef513245999bfb3464b96124640d22d#r1871548068)

2024-12-13 05:23 UTC, vg-27 commented on src/api_impl.rs
```suggestion
let gateways_contract = GatewaysContract::new(
        app_state.gateways_contract_addr,
        common_chain_http_provider.clone(),
    );
```

2024-12-13 05:23 UTC, vg-27 commented on src/api_impl.rs
> +            common_chain_http_provider.clone(),
```suggestion
```

2024-12-13 05:29 UTC, vg-27 commented on src/api_impl.rs
> +        drop(gateways_contract);
```suggestion

```

2024-12-23 08:24 UTC, arnav-deep commented on src/common_chain_interaction.rs
> +        txn_data.extend(encoded_tokens[32..].to_vec());
Done

2024-12-23 08:36 UTC, arnav-deep commented on src/api_impl.rs
Done

2024-12-23 08:42 UTC, arnav-deep commented on src/api_impl.rs
> +        drop(gateways_contract);
Done

2024-12-23 08:42 UTC, arnav-deep commented on src/api_impl.rs
> +            common_chain_http_provider.clone(),
Done

2024-12-23 09:29 UTC, vg-27 requested changes

2024-12-23 09:29 UTC, vg-27 commented on src/common_chain_interaction.rs
> +    use alloy::dyn_abi::DynSolValue;
is this change needed?

2024-12-23 09:29 UTC, vg-27 commented on src/api_impl.rs
> +    let registration_events_listener_active_guard = app_state
why is this guard needed?

2024-12-23 09:29 UTC, vg-27 commented on src/api_impl.rs
> +        drop(request_chains_data);
does it need to be dropped explicitly?

2024-12-23 09:29 UTC, vg-27 commented on src/api_impl.rs
> +            return HttpResponse::BadRequest().body("Gas wallet updated!");
It is failing http request because of some sync issue. Can't it be made synchronous, like while creating contract client object, any update to gas key should be on hold.

2024-12-24 11:15 UTC, arnav-deep commented on src/api_impl.rs
> +        drop(request_chains_data);
No. Updated.

2024-12-24 11:21 UTC, arnav-deep commented on src/common_chain_interaction.rs
> +    use alloy::dyn_abi::DynSolValue;
Yeah. The module code doesn't use DynSolValue anymore because of code changes. Tests still use them, so it needs to be explicitly imported here since `super::*` doesn't have that import anymore

2024-12-24 11:22 UTC, arnav-deep commented on src/api_impl.rs
> +    drop(registration_events_listener_active_guard);
Updated

2024-12-24 11:28 UTC, arnav-deep commented on src/api_impl.rs
> +        drop(request_chain_data_hashmap);
Not needed. Updated

2024-12-24 11:29 UTC, arnav-deep commented on src/api_impl.rs
> +    drop(registration_events_listener_active_guard);
Yeah, because this write lock is taken without involving any writes and is not being used. So if not explicitly dropped, the write lock will be shown as an unused variable. Purpose for this lock mentioned in the comment below.

2024-12-24 11:40 UTC, arnav-deep commented on src/api_impl.rs
> +            return HttpResponse::BadRequest().body("Gas wallet updated!");
Updated to use the signer update fn instead of throwing error.

2024-12-24 11:42 UTC, arnav-deep commented on src/api_impl.rs
> +    let registration_events_listener_active_guard = app_state
This guard describes the start of creating the contracts_client the first time. If this guard is not taken here, then while the contracts client is being built with the previous signer, the signer can be updated midway, and since the contracts client has not been updated yet, we would not process the update logic of the mutable config.

So this is basically to synchronise the contracts client and update of the mutable config.

2024-12-24 11:55 UTC, vg-27 commented on src/api_impl.rs
> +    let registration_events_listener_active_guard = app_state
I understand that. But it needs restructuring of locks, changing their name and purposes.

2024-12-24 11:58 UTC, vg-27 approved these changes, later dismissed
LG

2024-12-24 12:10 UTC, arnav-deep commented on src/api_impl.rs
> +    let registration_events_listener_active_guard = app_state
Yeah. This was repurposed here and new usage added. Will update the name to better reflect the usage.

2024-12-24 12:37 UTC, vg-27 requested changes

2024-12-24 12:37 UTC, vg-27 commented on src/api_impl.rs
> -    drop(registration_events_listener_active_guard);
shouldn't we drop wallet_gaurd before this, reverse ordering in drop. Also, explicit drop not required.

2024-12-25 05:39 UTC, arnav-deep commented on src/api_impl.rs
> -    drop(registration_events_listener_active_guard);
Yeah, this guard is not in use anymore.

2024-12-25 05:50 UTC, vg-27 submitted a review, later dismissed

2024-12-25 07:37 UTC, vg-27 approved these changes
LG.

2024-12-25 07:37 UTC, merged